# Generated by Django 5.1.7 on 2025-04-02 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bicycle_id', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(default='available', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bicycles/')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.bicycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
